service: aws-node-express-api-project
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    ACCOUNT_SID: ${env:ACCOUNT_SID}
    AUTH_TOKEN: ${env:AUTH_TOKEN}
    NUMBER_FROM_SEND_MESSAGE: ${env:NUMBER_FROM_SEND_MESSAGE}
  region: 'us-east-2'

package:
  excludeDevDependencies: true

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'
      
plugins:
  - serverless-offline
  - serverless-dotenv-plugin